import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

 const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LibFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex-row">
        <Sidebar />
      <main className="flex-1 ml-64 p-8 min-h-screen bg-gray-50">
        {children}
      </main>
      </body>
    </html>
  );
}
